hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path("<int:page>", views.main, name="root_paginate"),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('authoradd/', views.author, name='author'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    path("author/<str:fullname>", views.author_page, name="author"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=150, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag, related_name="tags")
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return f"{self.quote}"

    def show_tags(self):
        tag = self.tags.all()
        return tag

    def show_quote_author(self):
        return self.author

quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, ModelMultipleChoiceField, SelectMultiple
from .models import Tag, Quote, Author


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=125,
                     required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput())
    author = ModelChoiceField(required=False, queryset=Author.objects.all(), widget=SelectMultiple(
        attrs={"class": "form-select", "size": "7"}))
    tags = CharField(required=False, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=250, widget=TextInput())
    born_date = CharField(widget=TextInput())
    born_location = CharField(widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .utils import get_mongodb
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import Author, Tag, Quote
from .forms import TagForm, QuoteForm, AuthorForm


def main(request, page=1):
    quotes = Quote.objects.filter().all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={"quotes": quotes_on_page})


@login_required()
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})


@login_required()
def quote(request):
    tags = Quote.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_note = form.save()
            form.save()
            choice_tags = Tag.objects.filter(
                name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/quote.html', {"tags": tags, 'form': form})

    return render(request, 'quotes/quote.html', {"tags": tags, 'form': QuoteForm()})


@login_required()
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/authoradd.html', {'form': form})

    return render(request, 'quotes/authoradd.html', {'form': AuthorForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotes/detail.html', {"quote": quote})


@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quotes:main')


def author_page(request, fullname):
    authors = get_object_or_404(Author, fullname=fullname)

    return render(request, "quotes/author.html", {"author": authors})

quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    {% if user.is_authenticated %}
    <ul>
        <li><a href="{% url 'quotes:quote' %}" role="button">Add quote</a></li>
        <li><a href="{% url 'quotes:author' %}" role="button">Add author</a></li>
        <li><a href="{% url 'quotes:tag' %}" role="button">Add tag</a></li>
    </ul>
    <ul>
        <li>Welcome <b>{{ user.username }}!</b></li>
        <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
        <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
        <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
    </ul>

    {% endif %}
</nav>

<h4>{{ author.fullname }}</h4>
Born {{ author.born_date }} {{ author.born_location }}
<hr>
<h4>About author</h4>
{{ author.description }}

{% endblock %}

quotes/templates/quotes/authoradd.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author full name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author description:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework-10</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="/login" class="btn btn-primary">SignUp</a>
                    <a href="/login" class="btn btn-primary">LogIn</a>
                    <a href="/login" class="btn btn-primary">LogOut</a>
                </p>
            </div>
        </div>
        {% block content %}
        {% endblock %}

    </div>
</body>

</html>

quotes/templates/quotes/detail.html
{% extends "quotes/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{quote.author}}</h1>
<p>Quote: <b>{{quote.text}}</b></p>
<p>Tags: <small> {{ quote.tags|tags }} </small></p>
{% endblock %}

quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>HomeWork-10</title>
    <link rel="stylesheet" href="http://quotes.toscrape.com/static/bootstrap.min.css">
</head>

<body>
    <main class="container">

        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quotes:quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quotes:author' %}" role="button">Add author</a></li>
                <li><a href="{% url 'quotes:tag' %}" role="button">Add tag</a></li>
            </ul>
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>

            {% endif %}
        </nav>


        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
                <a href="/author/{{quote.show_quote_author}}">(about)</a>
            </span>

        </div>
        {% if user.is_authenticated %}
        <ul>
            <li>
                <a href="{% url 'quotes:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
            </li>
        </ul>
        {% endif %}
        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </main>
</body>

</html>

quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            {{ form.tags }}
        </label>

    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>

{% endblock %}